---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/settings.js
  label: Site Details
  match: "**/*"
- type: directory
  path: content/project
  label: Projects
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - projects
- type: directory
  path: content/blog
  label: Blogs
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - blogs
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - PORT=8080
  preview_output_directory: __sapper__/dev
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
